name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm ci
      - name: eslint checks
        run: |
          npm run lint
      - name: npm test
        run: |
          npx tsc
          npm run test-unit
      - name: Coverage test
        run: |
          npm run coverage
      - name: Build
        run: |
          npm run build
          npm run roll
      - name: Get API Keys
        uses: nowactions/envsubst@v1
        with:
          input: ./screepsNoCreds.yml
          output: ./.screeps.yml
        env:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Deploy
        run: |
          npm run push
